spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 4da20ff3ca74c6e58f89
            clientSecret: fd4185511ff07e4418e80405cafdbf68b34e1f4b
#            redirectUri: http://localhost:8080/user.html
#            redirectUri: https://www.hao123.com/
# ...
logging:
  level.org.springframework.security: debug
